//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uploaded_Files
    {
        public int File_ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string File_Path { get; set; }
    }
}
